In [ ]:
# Numpy Attributes and Advanced Pandas Operations

# টপিক:

# Data Cleaning with Pandas
# Handling Missing Data
# Dropping and Filling Data
# Basic Data Aggregations in Pandas (sum(), mean(), median(), count())

In [1]:
import pandas as pd
import numpy as np

In [131]:
df = pd.DataFrame({
    'Name': ['Alice', 'Bob', np.nan, 'Daisy', 'Ethan'],
    'Age': [25, np.nan, 29, 22, np.nan],
    'salary': [50000, 60000, np.nan, 58000, 62000]
})

In [132]:
df.head()

Name   Age   salary
0  Alice  25.0  50000.0
1    Bob   NaN  60000.0
2    NaN  29.0      NaN
3  Daisy  22.0  58000.0
4  Ethan   NaN  62000.0

In [6]:
df = data.dropna()

In [7]:
data_dropna.head()

Name   Age   salary
0  Alice  25.0  50000.0
3  Daisy  22.0  58000.0

In [95]:
data = data.fillna(
    {
     'Name': 'Unknown',
        'Age': data['Age'].mean(),
        'salary': 0
    }
)

In [11]:
data_filled.head()

Name        Age   salary
0    Alice  25.000000  50000.0
1      Bob  25.333333  60000.0
2  Unknown  29.000000      0.0
3    Daisy  22.000000  58000.0
4    Ethan  25.333333  62000.0

In [17]:
data_filled['Age'] = data_filled['Age'].astype(int)
data_filled['salary'] = data_filled['salary'].astype(int)

In [18]:
data_filled.head()


Name  Age  salary
0    Alice   25   50000
1      Bob   25   60000
2  Unknown   29       0
3    Daisy   22   58000
4    Ethan   25   62000

In [21]:
np_array = np.array([[1, 2, 3], [4, 5, 6]])

In [22]:
np_array

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
reshape_array = np_array.reshape(3, 2)

In [24]:
reshape_array

array([[1, 2],
       [3, 4],
       [5, 6]])

In [25]:
reshape_array = np_array.reshape(-1)

In [26]:
reshape_array

array([1, 2, 3, 4, 5, 6])

In [28]:
reshape_array = np_array.reshape(1, 6)

In [29]:
reshape_array

array([[1, 2, 3, 4, 5, 6]])

In [30]:
reshape_array[0]

array([1, 2, 3, 4, 5, 6])

In [47]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

In [48]:
a

array([[1, 2],
       [3, 4]])

In [49]:
b

array([[5, 6],
       [7, 8]])

In [54]:
d_stacked

array([[[1, 5],
        [2, 6]],

       [[3, 7],
        [4, 8]]])

In [43]:
v_stacked = np.vstack([a, b])

In [35]:
v_stacked

array([[1, 2],
       [3, 4],
       [5, 6]])

In [50]:
h_stacked = np.hstack([a, b])

In [51]:
h_stacked

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [52]:
d_stacked = np.dstack([a, b])

In [53]:
d_stacked

array([[[1, 5],
        [2, 6]],

       [[3, 7],
        [4, 8]]])

In [57]:
np_array = np.array([[[1,2, 4, 6], [2, 4, 5, 6]], [[5,6, 6, 7], [7, 8, 6, 7]]])

In [58]:
np_array

array([[[1, 2, 4, 6],
        [2, 4, 5, 6]],

       [[5, 6, 6, 7],
        [7, 8, 6, 7]]])

In [60]:
big_array = np.arange(10)

In [61]:
big_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
split_array = np.split(big_array, 5)

In [68]:
split_array

[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]

In [64]:
split_array[0]

array([0, 1, 2, 3, 4])

In [65]:
split_array[1]

array([5, 6, 7, 8, 9])

In [69]:
sorted_array = np.array([10, 20, 30, 40])

In [72]:
pos = np.searchsorted(sorted_array, 15)

In [73]:
pos

np.int64(1)

In [87]:
sorted_array = np.array([101, 200, 30, 41])

In [88]:
even = np.where(sorted_array % 2 == 0)

In [89]:
even

(array([1, 2]),)

In [96]:
data.head()

Name        Age   salary
0    Alice  25.000000  50000.0
1      Bob  25.333333  60000.0
2  Unknown  29.000000      0.0
3    Daisy  22.000000  58000.0
4    Ethan  25.333333  62000.0

In [97]:
sorted_data = data.sort_values(by='salary', ascending=True)

In [98]:
sorted_data.head()

Name        Age   salary
2  Unknown  29.000000      0.0
0    Alice  25.000000  50000.0
3    Daisy  22.000000  58000.0
1      Bob  25.333333  60000.0
4    Ethan  25.333333  62000.0

In [109]:
arr = np.array([6, 3, 8, 0])

In [110]:
arr

array([6, 3, 8, 0])

In [111]:
print(np.sort(arr)[::-1])

[8 6 3 0]


In [112]:
arr = np.array([True, True, False, True])

In [113]:
print(np.sort(arr)[::-1])

[ True  True  True False]


In [129]:
arr = np.array(["Banana", "Cherry", "Apple", "mango"])

In [130]:
print(np.sort(arr)[::-1])

['mango' 'Cherry' 'Banana' 'Apple']
