# NumPy Essentials Practice Exercises Overview:
Time to test the knowledge on NumPy. Lets start with simple task and move on to more challenging ones!<br>
**Good Luck**<br>

&#9758; *Please note, there are several ways to get the required output, so your code could be different then what is provided in this notebook. <br>As long as you are getting the tasks done, it is fine at this stage. *

**1. What is the major difference between "`Vector`" and "`Matrix`"?**

The major difference between vector and matrix is,<br>
* Vector is a one dimentional array, a single row
  * example: [1, 2, 3]
* While, matrix is a two dimentional array, comprising multiple row or colunm
  * example [[1, 2, 3],[4, 5, 6]]

**2. How to import `NumPy` library?** 

In [14]:
# To avoid overwriting the output, please code here 
import numpy as np

**3. Convert the given Python list into NumPy array and check its data type**

In [3]:
list_1 = [1,2,3,4,5]

In [18]:
# To avoid overwriting the output, please code here 
arr = np.array(list_1)
(arr, type(arr))

(array([1, 2, 3, 4, 5]), numpy.ndarray)

(array([1, 2, 3, 4, 5]), numpy.ndarray)

**4. Generate `array [0,1,2,3,4,5]` using NumPy built-in function, `arange()`**

In [20]:
# To avoid overwriting the output, please code here 
arr = np.arange(0, 6)
arr

array([0, 1, 2, 3, 4, 5])

array([0, 1, 2, 3, 4, 5])

**5. Generate an `array of "5" zeros`**

In [21]:
# To avoid overwriting the output, please code here 
arr = np.zeros(5)
arr

array([0., 0., 0., 0., 0.])

array([ 0.,  0.,  0.,  0.,  0.])

**6. Generate the following `matrix`.**

In [22]:
# To avoid overwriting the output, please code here 
mat = np.zeros((3, 4))
mat

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

**7. Generate** `[1.,1.,1.,1.,1.]` **using NumPy built-in function?**

In [28]:
# To avoid overwriting the output, please code here 
one = np.ones(5)
print(one)

[1. 1. 1. 1. 1.]


[ 1.  1.  1.  1.  1.]


**8. Generate an array of "5" tens.**

In [27]:
# To avoid overwriting the output, please code here
ten = np.full(5, 10.)
ten

array([10., 10., 10., 10., 10.])

array([10., 10., 10., 10., 10.])

**9. Use `arange()` to generate an array of even numbers between 50 and 100.**<br>
*50 and 100 are not included*

In [29]:
# To avoid overwriting the output, please code here 
even = np.arange(52, 100, 2)
even

array([52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84,
       86, 88, 90, 92, 94, 96, 98])

array([52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84,
       86, 88, 90, 92, 94, 96, 98])

**10. Generate an array of 10 linearly spaced points between 0 and 1.**<br>
**Output step size as well?**

In [35]:
# To avoid overwriting the output, please code here
arr = np.linspace(0, 1, 10)
step_size = arr[1] - arr[0]
(arr, float(step_size))

(array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
        0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ]),
 0.1111111111111111)

(array([ 0.        ,  0.11111111,  0.22222222,  0.33333333,  0.44444444,
         0.55555556,  0.66666667,  0.77777778,  0.88888889,  1.        ]),
 0.1111111111111111)

**11. Perform the following tasks:**
* Generate a **`vector array of 25`** numbers using **`arange()`**
* write a code to convert the vector array into **`2-D matrix using reshape`**
* can we use **`shape`** instead of reshape as well?

In [38]:
# To avoid overwriting the output, please code here 
vec = np.arange(25)
vec

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [22]:
# Generating vector array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [39]:
# To avoid overwriting the output, please code here 
mat = vec.reshape(5, 5)
mat

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [24]:
# reshape to convert into 2-d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [40]:
# To avoid overwriting the output, please code here
vec.shape = (5, 5)
vec

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [26]:
# Using shape

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

**12. Please generate the following matrix.**

In [42]:
# To avoid overwriting the output, please code here 
vec = np.arange(0.1, 2.6, 0.1)
mat = vec.reshape(5, 5)
mat

array([[0.1, 0.2, 0.3, 0.4, 0.5],
       [0.6, 0.7, 0.8, 0.9, 1. ],
       [1.1, 1.2, 1.3, 1.4, 1.5],
       [1.6, 1.7, 1.8, 1.9, 2. ],
       [2.1, 2.2, 2.3, 2.4, 2.5]])

array([[0.1, 0.2, 0.3, 0.4, 0.5],
       [0.6, 0.7, 0.8, 0.9, 1. ],
       [1.1, 1.2, 1.3, 1.4, 1.5],
       [1.6, 1.7, 1.8, 1.9, 2. ],
       [2.1, 2.2, 2.3, 2.4, 2.5]])

**13. Write a code to generate the output below, use "`linspace()`" and "`print()`"**

In [52]:
# To avoid overwriting the output, please code here
vec = np.linspace(0, 24, 25, dtype=int)
mat = vec.reshape(5, 5)
print(repr(mat))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

**14. What is the main difference between `linspace()` and `arange()`?**

The main difference between linspace() and arange() is:
* linspace() generate a specified number of points evenly spaced between a start and end value(inclusive by default).
  * syntax: np.linspace(start, stop, `num`)
  * example: np.linspace(0, 1, 5) → [0., 0.25, 0.5, 0.75, 1.]
* Generate values with a specified step size between start and end (end exclusive).
  * syntax: np.linspace(start, stop, `step_size`)
  * np.arange(0, 1, 0.25) → [0., 0.25, 0.5, 0.75]


**15. How to generate a single random integer number using NumPy built-in function?**

In [ ]:
# To avoid overwriting the output, please code here
random_number = np.random.randint(low, high)
random_number

6

**16. Write a code to generate a 7x5 matrix of 35 random numbers? use rand here** <br>
*Notice, there are no ( ) in the output matrix!*

In [73]:
# To avoid overwriting the output, please code here
mat = np.random.rand(7, 5)
print(mat)

[[0.82385434 0.09275473 0.89000367 0.10653177 0.924649  ]
 [0.5384528  0.37576907 0.45017415 0.11432832 0.79080576]
 [0.11335697 0.14810581 0.84674981 0.0583163  0.92478297]
 [0.1408647  0.53603288 0.48570424 0.78129362 0.52259844]
 [0.68403878 0.94769744 0.75013584 0.74083941 0.41210491]
 [0.00459672 0.63711188 0.44462953 0.40619098 0.03511858]
 [0.23523577 0.08685551 0.76674299 0.47593827 0.84706483]]


[[ 0.99598801  0.07546767  0.17484793  0.25229956  0.4693597 ]
 [ 0.5591561   0.5007227   0.93630239  0.48747691  0.78658124]
 [ 0.98923838  0.04124599  0.71326198  0.51252888  0.36130539]
 [ 0.11558779  0.52914213  0.31134907  0.8047612   0.25759207]
 [ 0.87331331  0.77104413  0.960445    0.1732589   0.83339285]
 [ 0.99839604  0.78268012  0.66487603  0.14509928  0.05670129]
 [ 0.15932364  0.848172    0.51343887  0.06309231  0.29250649]]


**17. Generate the following matrix using NumPy's built-in method for identity matrix.**

In [75]:
i_mat = np.eye(5)
result = 5 * i_mat
result

array([[5., 0., 0., 0., 0.],
       [0., 5., 0., 0., 0.],
       [0., 0., 5., 0., 0.],
       [0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 5.]])

array([[5., 0., 0., 0., 0.],
       [0., 5., 0., 0., 0.],
       [0., 0., 5., 0., 0.],
       [0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 5.]])

### You must be feeling comfortable using NumPy now!
# Great Job and Good Luck 