In [1]:
list1 = [1, 2, 3]
list2 = [4, 5, 6]
print(list1 + list2)

[1, 2, 3, 4, 5, 6]


In [2]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print(arr1 + arr2)

[5 7 9]


In [3]:
menu = np.array(['cheese', 'bbq', 'veg', 'spicy'])
print(menu)

['cheese' 'bbq' 'veg' 'spicy']


In [5]:
prices = [100, 200, 150, 220]
prices = prices * 0.8
print(prices)

TypeError: can't multiply sequence by non-int of type 'float'

In [8]:
prices_np = np.array([100.8, 200, 150, 220])
discounted_price = prices_np * 0.8
discounted_price

array([ 80.64, 160.  , 120.  , 176.  ])

In [11]:
empty_table = np.zeros((3, 3))
print(empty_table)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [12]:
empty_table = np.ones((3, 3))
print(empty_table)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [14]:
bbq_boxes = np.full((2,3), 'bbq')
print("BBQ boxes:\n", bbq_boxes)

BBQ boxes:
 [['bbq' 'bbq' 'bbq']
 ['bbq' 'bbq' 'bbq']]


In [17]:
surprise_toppings = np.random.rand(2,3)
print(surprise_toppings)

[[0.23443124 0.63223564 0.67499454]
 [0.49846459 0.96481695 0.21116871]]


In [24]:
kids_orders = np.random.randint(1, 8, (2, 3))
print(kids_orders)

[[1 6 1]
 [2 1 5]]


In [26]:
signature_pizzas = np.identity(4)
print(signature_pizzas)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [30]:
delivery_times = np.arange(0, 70, 15)
print(delivery_times)

[ 0 15 30 45 60]


In [29]:
cooking_shifts = np.linspace(0, 70, 5)
print(cooking_shifts)

[ 0.  17.5 35.  52.5 70. ]


In [41]:
orders = np.array(['cheese', 'veg', 'spicy', 'bbq'])
print(orders[2])
print(orders[:2])
print(len(orders))

spicy
['cheese' 'veg']
4


In [43]:
orders = np.array([
    ['cheese', 'veg'],
    ['spicy', 'bbq']
])
print(orders[0,1])

veg


In [63]:
print(orders[:2,0])

['cheese' 'spicy']


In [67]:
sales = np.array([120, 150, 90, 200])
print("Max sales", np.max(sales))
print("Max seller index", np.argmax(sales))
print("Min sales", np.min(sales))
print("Min seller index", np.argmin(sales))

Max sales 200
Max seller index 3
Min sales 90
Min seller index 2
